export const DOCUMENT_TYPES = Object.freeze({
  saleLogo: 'sale_logo',
  saleDocument: 'sale_document',
  kycIdDocument: 'kyc_id_document',
  kycProofOfAddress: 'kyc_poa',
  kycSelfie: 'kyc_selfie',
  kycAvatar: 'kyc_avatar',
  kycTaxReturns: 'kyc_tax_returns',
  kycOriginationCertificate: 'company_origination_certificate',
  kycInvestmentPresentation: 'kyc_investment_presentation',
  kycProofOfInvestor: 'kyc_proof_investor',
  kycShareholdersCertificate: 'kyc_shaholders_certificate',
  kycAnnualReport: 'kyc_annual_report',
  kycMemorandium: 'kyc_memorandium',
  kycSignatoriesAuthorization: 'kyc_signatories_authorization',
  kycOrganizationChart: 'kyc_organization_chart',
  kycBusinessModel: 'kyc_business_model',
  passport: 'passport',
  driving_license: 'driving_license',
  identity_card: 'identity_card',
  residence_permit: 'residence_permit',
  assetTerms: 'token_terms',
  assetLogo: 'asset_logo',
  healthcareDocument: 'healthcare_document',
})
