const TYPES = Object.freeze({
  public: 'general_public',
  private: 'general_private',
})

export const DOCUMENT_TYPES = Object.freeze({
  saleLogo: TYPES.public,
  saleDocument: TYPES.public,
  kycIdDocument: TYPES.private,
  kycProofOfAddress: TYPES.private,
  kycSelfie: TYPES.private,
  kycAvatar: TYPES.public,
  kycTaxReturns: TYPES.private,
  kycOriginationCertificate: TYPES.private,
  kycInvestmentPresentation: TYPES.private,
  kycProofOfInvestor: TYPES.private,
  kycShareholdersCertificate: TYPES.private,
  kycAnnualReport: TYPES.private,
  kycMemorandium: TYPES.private,
  kycSignatoriesAuthorization: TYPES.private,
  kycOrganizationChart: TYPES.private,
  kycBusinessModel: TYPES.private,
  passport: TYPES.private,
  driving_license: TYPES.private,
  identity_card: TYPES.private,
  residence_permit: TYPES.private,
  assetTerms: TYPES.public,
  assetLogo: TYPES.public,
  healthcareDocument: TYPES.private,
})

export const DOCUMENT_TYPES_TRANSLATION_IDS = Object.freeze({
  [DOCUMENT_TYPES.saleLogo]: 'document-types.sale-logo',
  [DOCUMENT_TYPES.saleDocument]: 'document-types.sale-document',
  [DOCUMENT_TYPES.assetTerms]: 'document-types.asset-terms',
  [DOCUMENT_TYPES.assetLogo]: 'document-types.asset-logo',
  [DOCUMENT_TYPES.kycIdDocument]: 'document-types.kyc-id-document',
  [DOCUMENT_TYPES.kycProofOfAddress]: 'document-types.kyc-proof-of-address',
  [DOCUMENT_TYPES.kycSelfie]: 'document-types.kyc-selfie',
  [DOCUMENT_TYPES.kycAvatar]: 'document-types.kyc-avatar',
  [DOCUMENT_TYPES.kycTaxReturns]: 'document-types.kyc-tax-returns',
  [DOCUMENT_TYPES.kycOriginationCertificate]: 'document-types.kyc-origination-certificate',
  [DOCUMENT_TYPES.kycInvestmentPresentation]: 'document-types.kyc-investment-presentation',
  [DOCUMENT_TYPES.kycProofOfInvestor]: 'document-types.kyc-proof-of-investor',
  [DOCUMENT_TYPES.kycShareholdersCertificate]: 'document-types.kyc-shareholders-certificate',
  [DOCUMENT_TYPES.kycAnnualReport]: 'document-types.kyc-annual-report',
  [DOCUMENT_TYPES.kycMemorandium]: 'document-types.kyc-memorandum',
  [DOCUMENT_TYPES.kycSignatoriesAuthorization]: 'document-types.kyc-signatories-authorization',
  [DOCUMENT_TYPES.kycOrganizationChart]: 'document-types.kyc-organization-chart',
  [DOCUMENT_TYPES.kycBusinessModel]: 'document-types.kyc-business-model',
  [DOCUMENT_TYPES.passport]: 'document-types.passport',
  [DOCUMENT_TYPES.driving_license]: 'document-types.driving-license',
  [DOCUMENT_TYPES.identity_card]: 'document-types.identity-card',
  [DOCUMENT_TYPES.residence_permit]: 'document-types.residence-permit',
  [DOCUMENT_TYPES.assetTerms]: 'document-types.asset-terms',
  [DOCUMENT_TYPES.assetLogo]: 'document-types.asset-logo',
})
