#!/bin/sh

set -ex

if [ -z "$CI_COMMIT_TAG" ];
then
  BUILD_VERSION=$CI_COMMIT_SHORT_SHA
else
  BUILD_VERSION=$CI_COMMIT_TAG
fi

docker build --build-arg BUILD_VERSION=$CI_COMMIT_REF_NAME --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
