export const vueRoutes = Object.freeze({
  // existing routes:
  app: { name: 'app' },
  auth: { name: 'auth' },
  login: { name: 'login' },
  verify: { name: 'verify' },
  fees: { name: 'app.fees' },
  operations: { name: 'app.operations' },
  signup: { name: 'signup' },
  recovery: { name: 'recovery' },
  settings: { name: 'app.settings' },
  verification: {
    name: 'app.verification',
    general: {
      name: 'app.verification.general',
    },
    corporate: {
      name: 'app.verification.corporate',
    },
  },
  security: { name: 'app.security' },
  dashboard: { name: 'app.dashboard' },
  issuance: { name: 'app.issuance' },
  assets: { name: 'app.assets' },
  balances: { name: 'app.balances' },
  assetsExplore: { name: 'app.assets-explore' },
  requests: {
    name: 'app.requests',
    assetCreation: { name: 'app.asset-creation' },
    fundCreation: { name: 'app.fund-creation' },
    preissuanceUpload: { name: 'app.preissuance-upload' },
  },
  // stubs:
  terms: { name: 'terms' },
  downloads: { name: 'downloads' },
  deposit: { name: 'app.deposit' },
  limits: { name: 'app.limits' },
  transfers: { name: 'app.transfers' },
  massTransfers: { name: 'app.mass-transfers' },
  withdrawal: { name: 'app.withdrawal' },
  history: { name: 'app.history' },
  trade: { name: 'app.trade' },
  issuanceCreation: { name: 'app.issuanceCreation' },
  sales: { name: 'app.sales' },
  mySales: { name: 'app.my-sales' },
})
