const mutations = {
  SET_FIRST_NAME: 'SET_FIRST_NAME',
  SET_LAST_NAME: 'SET_LAST_NAME',
  SET_DATE_OF_BIRTH: 'SET_DATE_OF_BIRTH',

  SET_ADDRESS_LINE_1: 'SET_ADDRESS_LINE_1',
  SET_ADDRESS_LINE_2: 'SET_ADDRESS_LINE_2',
  SET_ADDRESS_CITY: 'SET_ADDRESS_CITY',
  SET_ADDRESS_COUNTRY: 'SET_ADDRESS_COUNTRY',
  SET_ADDRESS_STATE: 'SET_ADDRESS_STATE',
  SET_ADDRESS_POSTAL_CODE: 'SET_ADDRESS_POSTAL_CODE',

  SET_ID_DOCUMENT_TYPE: 'SET_ID_DOCUMENT_TYPE',

  SET_DOCUMENT_AVATAR: 'SET_DOCUMENT_AVATAR',
  SET_DOCUMENT_SELFIE: 'SET_DOCUMENT_SELFIE',
  SET_DOCUMENT_ID_DOC_FACE: 'SET_DOCUMENT_ID_DOC_FACE',
  SET_DOCUMENT_ID_DOC_BACK: 'SET_DOCUMENT_ID_DOC_BACK',
}

const getters = {
  blobData: 'blobData',
}

export const types = {
  ...getters,
  ...mutations,
}
