import { i18n } from '../i18n/index'

export const PAGES_NAMES = Object.freeze({
  dashboard: i18n.lbl_dashboard(),
  deposit: i18n.lbl_deposit(),
  limits: i18n.lbl_limits(),
  withdraw: i18n.lbl_withdraw(),
  send: i18n.lbl_send(),
  exploreTokens: i18n.lbl_explore_tokens_page(),
  createToken: i18n.lbl_create_token_page(),
  createIssuance: i18n.lbl_create_issuance_page(),
  preIssuance: i18n.lbl_upload_preissuance_page(),
  exploreSales: i18n.lbl_explore_sales(),
  createSale: i18n.lbl_create_sale_page(),
  requests: i18n.lbl_requests(),
  history: i18n.lbl_history(),
  trade: i18n.lbl_trade(),
  verification: i18n.lbl_verification(),
  settings: i18n.lbl_settings_page(),
  help: i18n.lbl_help(),
  downloads: i18n.lbl_downloads(),
  iosInstallGuide: i18n.lbl_ios_install_guide(),
  terms: i18n.lbl_terms(),
  massTransfer: i18n.lbl_mass_transfer(),
  uploadDocuments: i18n.lbl_upload_document(),
  viewDocument: i18n.lbl_view_document(),
  exploreDocuments: i18n.lbl_explore_documents(),
  checkDocument: i18n.lbl_find_document(),
  updateToken: i18n.lbl_update_token()
})
